import time
import socket
import threading
import re
import math
import numpy as np
import os
import asyncio
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

os.system("kill-port 33500")

device_name = "Drone-2"
device_ip = "localhost"
device_port = 33500

discovery_ip = "localhost" 
discovery_port = 33333

# devices are stored as device: (ip, port)
knownDevices = {}
forwardingTable = {} # device + "/" + data: address
interestForwards = {} #{} # interest code: address
interestRequests = {} # interest codes generated by this device
dataForwards = {} # interest code: address
DataReceived = {} # intereset code: data
requestCodeNum = 0

# ECC key pair generation
private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
public_key = private_key.public_key()

# Serialization of ECC public key
ecc_public_key_bytes = public_key.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo
)

# bind to device unique port
device_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
device_socket.bind((device_ip, device_port))
print("UDP socket connected")


class DroneNode:
    def __init__(self):
        self.destination = (0,0)
        self.nearest_charger = ""
        self.gps = (0, 0) # Latitude, Longitude of TCD
        self.battery_level = 100 # Battery percentage
        self.propeller_speed = 0 # RPM
        self.barometric_pressure = 1013 # hPa (of sea-level)
        self.water_release = False
        self.payload_release = False
        self.speaker_status = False
        self.flashlight_status = False

    def simulate_sensor_data(self):
            while True:
                self.gps = (self.gps[0] + 2, self.gps[1] - 1)
                self.battery_level -= 5
                if(self.propeller_speed < 10000):
                    self.propeller_speed += 2000
                if(self.barometric_pressure > 920):
                    self.barometric_pressure -= 20
                time.sleep(2)

    def drone_logic(self):
        while True:
            if(self.battery_level <= 90):
                print("attempting to contact charger")

                available_charger_locations = []
                
                # Try to find a charger
                for device in knownDevices:
                    if(device.split("-")[0] == "Charger"):
                        # Send a request to this device
                        code = send_interest_packet("usage_status", device)
                        time.sleep(.5)

                        # if charger is free, get gps
                        if code in DataReceived:
                            if DataReceived[code] == "False":
                                code = send_interest_packet("gps", device)
                                time.sleep(.5)

                                if code in DataReceived:
                                    # extract numbers from string
                                    location = re.findall(r'-?\d+\.\d+|-?\d+', DataReceived[code])
                                    available_charger_locations.append([int(i) for i in location])
                                    

                if len(available_charger_locations) > 0:
                    self.destination = get_min_distance(available_charger_locations, self.gps)

                print("current destination:", self.destination)

            time.sleep(1)

def get_min_distance(locations, drone_position):
    distances = []
    for point in locations:
        distances.append(math.sqrt((int(drone_position[0]) - int(point[0]))**2 + (int(drone_position[1]) - int(point[1]))**2))
    return locations[np.argmin(distances)]

# ECC encryption and decryption functions
def encrypt_data(public_key, plaintext):
    iv = os.urandom(16)  # Initialization vector
    cipher = Cipher(algorithms.ChaCha20(iv), mode=modes.CFB8(), backend=default_backend())
    encryptor = cipher.encryptor()
    ciphertext = encryptor.update(plaintext.encode()) + encryptor.finalize()
    return iv + ciphertext

def decrypt_data(private_key, encrypted_data):
    iv = encrypted_data[:16]
    ciphertext = encrypted_data[16:]
    cipher = Cipher(algorithms.ChaCha20(iv), mode=modes.CFB8(), backend=default_backend())
    decryptor = cipher.decryptor()
    plaintext = decryptor.update(ciphertext) + decryptor.finalize()
    return plaintext.decode()

def discovery():
    while True:
        discovery_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        discovery_message = encrypt_data(public_key, device_name)
        try:
            # Check if port is available
            discovery_socket.bind((discovery_ip, discovery_port))
            discovery_socket.settimeout(1)
            connection_time = time.time()

            # Hold the connection for 2 seconds to listen for incoming discovery messages
            while time.time() - connection_time < 5:
                try:
                    data, sender_address = discovery_socket.recvfrom(1024)
                    knownDevices[decrypt_data(private_key, data)] = sender_address
                except socket.timeout:
                    continue

            # Close socket to allow other devices to connect
            discovery_socket.close()
        except OSError as e:
            # Send discovery message to the receiver
            device_socket.sendto(discovery_message.encode(), (discovery_ip, discovery_port))

        time.sleep(3)


# send an interest packet for a piece of data on a different device
def send_interest_packet(data, device):
    global requestCodeNum
    requestCodeNum = requestCodeNum + 1
    requestCode = str(device_name)+str(requestCodeNum)
 
    packet = "interest"+"/"+requestCode+"/"+str(device)+"/"+str(data)
    encrypted_data_packet = encrypt_data(public_key, packet)

    interestRequests[requestCode] = [str(device), str(data)]

    # if no specific devices are mentioned in the call
    if device == "none":
        # check if data is in the forwarding table
        if str(device)+"/"+str(data) in forwardingTable:
                device_socket.sendto(encrypted_data_packet, forwardingTable[str(device)+"/"+str(data)])
                #awaitedAcks[requestCode] = [packet, time.time()]

        # if not perform flooding
        else:
            print(packet)
            for devices in knownDevices:
                device_socket.sendto(encrypted_data_packet, knownDevices[devices])

    else:
        device_socket.sendto(encrypted_data_packet, knownDevices[device])

    return requestCode


def handle_interests(message, address):
    encrypted_data = message.split('/')[1]
    decrypted_data = decrypt_data(private_key, encrypted_data)
    interest_code, requested_device, requested_data = decrypted_data.split('/')

    # if this is the requested device, send the info
    if requested_device == device_name:
        send_requested_data(decrypted_data, address)

    # else forward the packet if it hasnt been already
    elif interest_code not in interestForwards:

        interestForwards[interest_code] = address # add to list of unresolved interests
        print()

        # check if requested data is in forwarding table
        if str(requested_device)+"/"+str(requested_data) in forwardingTable:
            print("sending from table")
            device_socket.sendto(message.encode(), forwardingTable[str(requested_device)+"/"+str(requested_data)])
            #awaitedAcks[interest_code] = [message, time.time()]

        # if not perform flooding
        else:
            for device in knownDevices:
                if knownDevices[device] != address: # dont send the interest back to the sender
                    device_socket.sendto(message.encode(), knownDevices[device])


def handle_data(message, address):
    encrypted_data = message.split('/')[1]
    decrypted_data = decrypt_data(private_key, encrypted_data)
    interest_code, requested_device, requested_data = decrypted_data.split('/')

    # add sender to forwarding table
    forwardingTable[str(requested_device)+"/"+str(requested_data)] = address

    # if interest request was made by this device
    if interest_code in interestRequests:
        print("data received:", message)
        DataReceived[interest_code] = requested_data
        del interestRequests[interest_code]

    # if not forward to the correct device
    elif interest_code in interestForwards:
        device_socket.sendto(message.encode(), interestForwards[interest_code])
        #awaitedAcks[interest_code] = [message, time.time()]
        del interestForwards[interest_code]

    # if this data has not been requested perform flooding
    elif interest_code not in dataForwards:
        dataForwards[interest_code] = requested_data
        for device in knownDevices:
                if knownDevices[device] != address: # dont send the interest back to the sender
                    device_socket.sendto(message.encode(), knownDevices[device])


def send_requested_data(message, address):
    interest_code = message.split('/')[1]
    requested_device = message.split('/')[2]
    requested_data = message.split('/')[3]

    data_response = "data"+"/"+str(interest_code)+"/"+str(requested_device)+"/"+getattr(drone, requested_data)
    encrypted_response = encrypt_data(public_key, data_response)
    device_socket.sendto(encrypted_response, address)

def receive_messages():
    while True:
        print("awaiting messages")
        data, sender_address = device_socket.recvfrom(1024)
        print("Received connection: ", sender_address, data.decode())

        # check message is interset request or data
        if data.decode().split('/')[0] == "interest":
            handle_encrypted_interests(data.decode(), sender_address)

        elif data.decode().split('/')[0] == "data":
            handle_encrypted_data(data.decode(), sender_address)
        else:
            print("Unknown message type")

def handle_encrypted_interest(encrypted_message, address):
    decrypted_data = decrypt_data(private_key, encrypted_message.split('/')[1])
    handle_interests(decrypted_data, address)

def handle_encrypted_data(encrypted_message, address):
    decrypted_data = decrypt_data(private_key, encrypted_message.split('/')[1])
    handle_data(decrypted_data, address)

drone = DroneNode()

def main():

    sensor_data_thread = threading.Thread(target=drone.simulate_sensor_data)
    drone_logic_thread = threading.Thread(target=drone.drone_logic)
    discovery_thread = threading.Thread(target=discovery)
    receive_messages_thread = threading.Thread(target=receive_messages)

    sensor_data_thread.start()
    drone_logic_thread.start()
    discovery_thread.start()
    receive_messages_thread.start()

    #while True:
        #drone.drone_logic()
        #drone.simulate_sensor_data()
        #print(drone.battery_level)
        #print(knownDevices)
        #await asyncio.gather(discovery(), asyncio.sleep(1))

if __name__ == "__main__":
    main()